name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make build

    - name: Run tests
      run: make run

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: objects
        path: |
          wcwidth.o
          utf8util.o
          utf8string.o
